   create table if not exists notifications (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        booking_reference varchar(255) not null,
        message TEXT not null,
        notification_type varchar(255) not null check ((notification_type in ('EMAIL','SMS','WHATSAPP','TELEGRAM','MAX','SLACK'))),
        recipient varchar(255) not null,
        subject varchar(255) not null,
        primary key (id)
   );