   create table if not exists payments (
        amount numeric(38,2) not null,
        id bigint generated by default as identity,
        payment_date timestamp(6) not null,
        user_id bigint not null,
        booking_reference varchar(255) not null,
        failure_reason varchar(255),
        payment_gateway varchar(255) check ((payment_gateway in ('PAYPAL','STRIPE','PAYSTACK','FLUTTERWAVE'))),
        payment_status varchar(255) not null check ((payment_status in ('PENDING','COMPLETED','FAILED','REFUNDED','REVERSED'))),
        transaction_id varchar(255) not null unique,
        primary key (id)
   );