   create table if not exists rooms (
        id bigint generated by default as identity,
        capacity integer check ((capacity>=1)),
        price_per_night numeric(38,2),
        room_number integer unique check ((room_number>=1)),
        description varchar(255),
        image_url varchar(255),
        room_type varchar(255) not null check ((room_type in ('SINGLE','DOUBLE','SUIT','TRIPLE'))),
        search_vector TEXT,
        primary key (id)
   );