   create table if not exists users (
        is_active boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        phone_number varchar(255) not null unique,
        role varchar(255) check ((role in ('CUSTOMER','ADMIN'))),
        primary key (id)
   );