services:
  postgres_db:
    image: 'postgres:18.3-alpine'
    restart: always
    container_name: pg-hotel-booking-db
    environment:
      - 'POSTGRES_DB=hotel_bookings'
      - 'POSTGRES_PASSWORD=secret2026'
      - 'POSTGRES_USER=postgres'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    networks:
      - spring-hotel-booking-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
#    build: .
    # Format: username/project-name:tag
    image: caito25/hotelbooking:latest
    pull_policy: missing # Tells Docker to use the local Jib build first
    container_name: spring_hotel_booking_app
    ports:
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      # Overrides application.yml to use the 'db' service name instead of 'localhost'
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/hotel_bookings
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret2026
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - spring-hotel-booking-net

networks:
  spring-hotel-booking-net:
    driver: bridge

volumes:
  postgres_data: # Persists your database even if the container is removed