server:
  port: ${SERVER_PORT:9090} # Defaults to 9090 to match Jib/Compose
spring:
  application:
    name: HotelBooking

  # Postgres Connections
  datasource:
    # 'db' matches the service name in your docker-compose.yml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_bookings}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Options: non e, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    # Prevents Flyway from running 'DROP' commands (clean) in production
    clean-disabled: true

    # Allows Flyway to run again if a migration failed and you fixed the metadata
    repair-on-migrate: true

    # If someone manually changed the DB, this prevents the app from starting
    # until the migration scripts match the DB state exactly.
    validate-on-migrate: true

    # Useful if you are adding Flyway to an EXISTING database that already has tables
    #baseline-on-migrate: true
    #baseline-version: "1.0"

    # Set this to false if you have scripts that CANNOT run in a transaction
    # (like Postgres concurrent index creation)
    #group: false

    # How long to wait for a table lock before failing
    lock-retry-count: 10

    # Automatically clear and re-run migrations on every start (Careful!)
    #clean-on-validation-error: true

# Mail configuration for sending booking confirmations
  mail:
    host: smtp.gmail.com
    port: 587
    username: capfer27@gmail.com # represent your email address here, e.g., example@gmail.com
    password: jyri fxdz czop zqgt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # Ensure your app works with the health checks we set up earlier
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.flywaydb: DEBUG
    # Optional: If you want to see the low-level JDBC calls
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

# Generate a unique secret key for JWT signing (or use an environment variable)
jwt:
    # 40 characters is a good length for a secret key
    secret-key: ertYuiopASDFGHJKLzxcvbnmQWERTYUIOP123456
    expiration: 3600000 # 1 hour in milliseconds
    # 24 hours in milliseconds
    refresh-token-expiration: 86400000 // 7 days in milliseconds


