   create table if not exists bookings (
        check_in_date date not null,
        check_out_date date not null,
        total_price numeric(38,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        room_id bigint not null,
        user_id bigint not null,
        booking_reference varchar(255) not null unique,
        booking_status varchar(255) not null check ((booking_status in ('BOOKED','CHECKED_IN','CHECKED_OUT','CANCELLED'))),
        payment_status varchar(255) not null check ((payment_status in ('PENDING','COMPLETED','FAILED','REFUNDED','REVERSED'))),
        primary key (id)
   );